### ISSUE TITLE
array member lost all its member other than first one

### ISSUE THREAD

**Issue by suikabreaker** [exosite/lua-yaml#10]
```yaml
arr:
- prop1:
    subprop1: test
    subprop2:
      test: test
      test: {}
  prop2:
    test: test.test
  prop3:
  - test

```

only prop1 can be found in arr[1]
