### ISSUE TITLE
Add parsing for comments

### ISSUE THREAD

**Issue by MaxBrain** [exosite/lua-yaml#14]
Add ability to parse yaml like this

```yaml
key: #comment 1
   - value line 1
   #comment 2
   - value line 2
   #comment 3
   - value line 3
key2: 30 # comment 4
key3: "String value" # comment 5
key4: "#not a comment"

```
