### ISSUE TITLE
only decode the first block of yaml

### ISSUE THREAD

**Issue by aloisio31** [exosite/lua-yaml#7]
yaml:
```yaml
---
hooks:
  AfterInstall:
    - location: /Users/derekmorgan/src/deploy-plugin/afterinstall.sh
      timeout: 2
    - location: /Users/derekmorgan/src/deploy-plugin/afterinstall.sh
      timeout: 2
files:
  - source: ./my-file.txt
    destination: /temp
```
lua:
```lua
tprint(require('yaml').eval(s), 1)
  hooks:
    AfterInstall:
      1:
        location: /Users/derekmorgan/src/deploy-plugin/afterinstall.sh
        timeout: 2
      2:
        location: /Users/derekmorgan/src/deploy-plugin/afterinstall.sh
        timeout: 2
```
